### ISSUE TITLE
New NUHOL model with upgrade options

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#25]
Upgrades:
- More range [higher power usage (Should scale exponential in range)]
  - Or split in a deep and wide module
- Filter module? [ability to filter found ores]
- Power reduction [balance factor]
- Scanning improvement module [For detecting ores like silver, gold and platinum (Should require platinum to build, its for makeing the game more complex)]
  - Or slit to a module for each ore, but that is maybe too much?

**Comment by Fank** [comment]
@nukeguard what do you think, or what have you planned? How many upgrade modules should it be able to fit? A higher amount of upgrades will automatically increase the options you do.
If a higher amount of upgrades is planned, i would like to have a upgrade foreach ore.

**Comment by nukeguard** [comment]
replace is better, and I think I would add 4 upgrade spots to the new one, dimensions 2x2x4, and have the ports on opposing sides.

**Comment by nukeguard** [comment]
think 4 modules for that is just right, 
-range (obvious, distance increase from mining rig)
-filter (filter ore mined)
-power (reduce power cost)
-scanning (ability to scan precious metals) Au Ag Pl and modded ores (if possible)

-no upgrades attached only can find: U Fe Mg Si Co Ni

**Comment by Fank** [comment]
About the scanning i have something like `MyVoxelMaterialDefinition` so it should be possible.
So yea 4 should be fine.

We may add _U_ to scanning module only too.

About the model i found something for inspiration:
- that will match the "hammer" model & with upgrade "slots" https://3docean.net/item/scifi-locator/11876256
- this is a mining laser but i think it can be used as stationary like in the picture bottom left https://tec.artstation.com/projects/4lmql i'll record a video of it later, the animation is quite awesome.

**Comment by skyraze** [comment]
I'll redownload some 3D modeling tools and see if I can come up with
something. I have some experience with tools similar to this.
Note: I'm not the best modeler but I can whip something up for inspiration.

**Comment by nukeguard** [comment]
those two are great for inspiration, will go well with what I was thinking.

**Comment by Fank** [comment]
@nukeguard this is the second ones animation https://streamable.com/ogis4

**Comment by nukeguard** [comment]
I have this game, I have not gotten that far yet, but nice animation

**Comment by Fank** [comment]
Discussed with @nukeguard , new model will use OreDetector as base. Because it will do exactly the same as a ore detector only with upgrade support and nanite support.

**Comment by skyraze** [comment]
so far im liking the new one, though i still feel better if we get a small one similar to the current nuhol. something this massive works well as a planet miner or refuel depot for capital ships (currently have a layer of 20 nuhol miners on a lake bed to feed my capital ship when it runs low on fuel)

also something i noticed from the old nuhol, it will eat away at the blocks its on, meaning it will shut itself off when it eats the blocks holding it up. make it so it ignores anchoring points.

**Comment by skyraze** [comment]
so i just had an idea pop in my head while i was falling asleep, I was thinking along with the NUHOL miner, have a Heavy Fracking drill. 
a massive drill that is 4X4X10 large that can find and source out materials within a 3KM radius. it would require massive amounts of materials including ice and platinum, so you need to go into space first before you can use it on a planet.

it's a high maintenance, high payout device that needs Stone, Ice, and massive amounts of power (500MW). 
to get the idea, Ice is used to cool and lubricate the device, stone is used in conjunction with the ice to create fracturing fluid. then nanites do the rest of the work and grabs and return the ores. (This is the concept idea to make the drill make sense, just letting it detect ore and having the nanites grab it is enough, plus lowers the amount of CPU load needed to drill actual bores)

i'm still contemplating whether the drill will supply its own nanites or if you need a factory to do that.
I feel like needing factories to supply nanites is the way to go, that way you can have seperate ships use the drill wirelessly instead of having to connect to the station.

if it's possible, make it be able to only source out one pocket of ore at a time.
so if it finds a silver ore pocket and a gold ore pocket, you have to choose one or the other and not both at the same time. That also means if it finds two gold ore pockets, you have to choose between the two, not both together. that way the Overpowered nature of it is balanced by maintenance, power cost, and filtering.

**Comment by Fank** [comment]
My current state for the ore detector are:
- disabled/not functional/unpowered (should be red, static)
- enabled/idle (should be green, static)
- scanning (blue?, with animation?)

Scanning at a range of 240 meter take about 30sec

**Comment by skyraze** [comment]
Scanning should including some spinning dish or item, complete keeps the spinning item floating and pulsing green/blue

**Comment by nukeguard** [comment]
if there will be spinning part, then can make the center orb spin. 
so with the Mining rig, this will take upgrades like the facility or this will be the 5 upgrades that visually mesh with rig and make it larger?

**Comment by skyraze** [comment]
I believe the idea was to have 6 separate parts from the ore detector, 1
center piece, 4 side pieces, and a top piece. Fank has more info on this.

**Comment by Fank** [comment]
WTF?! the ore detector model is totally different to #47 !!!
The ore detector is 3x3x4 and #47 should be something around 20x20x30. So this issue is for the ore detector only, and the ore detector is designed for this use only.
The mining rig aka #47 is designed for larger use and has different abilities.
This was the 6th time i clarified it, if you still don't understand it for 100%, than write in mod dev channel in discord and ill explain you again what are planed functions behind it and what are they going to do.
:angry:

**Comment by SplenectomY** [comment]
Mining is up and running with the Nanite Ore Detector, functioning as expected with a few minor glitches I have to work out. The NUHOL is officially 100 percent replaced, as this now does all the nuhol did and more, even without the other, standalone "facility" that hasn't been implemented yet. Personally, I don't see a need for it at all. If it's going to a be a standalone block, then why wouldn't it be a separate mod? But I digress. This issue is done, as the whole point here was Nuhol replacement due to performance. The upgrade options have also been implemented and they work as expected. Separate issues should be brought up for any individual concerns.
