### ISSUE TITLE
Consumable nanites

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#28]
I was thinking about making nanites consumable, like ammo for turrets.
Each nanite will have its on item, which can also be stored in the cargo system.
And for that we will also need a "Factory" which will produce nanites of a given type.

This is for something later @nukeguard @skyraze what do you think?

**Comment by skyraze** [comment]
it would have to be a system that doesn't use more resources than it can create, since mining seems to be a major part of it. (from the people i play with, that's what they use for mainly)
if anything replacing the modules with cargo pods that carry only nanites, you can have nanites that you can allocate to specific tasks.

I personally think having to build nanites might not be the option to go towards, but having both power and resource management to keep nanites working is a good idea. it allows nanites to do the tedious tasks while requiring you to keep it maintained.

**Comment by nukeguard** [comment]
I agree with skyraze, not sure if making nanites consumable as an ammo type is the best option, nanite limit and power requirements should be sufficient.

**Comment by Fank** [comment]
But what about the lower power and add this, is it a possible balancing?

**Comment by Fank** [comment]
Maybe adding something like "yield" or "efficiency" upgrades so less material is needed.

**Comment by Jagernaut** [comment]
For me, the only reason why individual nanites should cost ressources is, if individual nanites can be destroyed.
