### ISSUE TITLE
Projector nanites not finishing jobs

### ISSUE THREAD

**Issue by raysilverstone** [nukeguard/NaniteConstructionSystem#4]
The Projector nanites are only placing the first component of each projected block then not finishing.  It's just leaving a skeleton ship.

**Comment by BAM5** [comment]
Can you upload a world save that exhibits this problem?

**Comment by raysilverstone** [comment]
What file exactly in my save fold would you need?  I tried it in easy start world with no mods and it still does it.  Only welds the first component of each block nothing else.

**Comment by BAM5** [comment]
You were sure to load it with building materials right?

**Comment by raysilverstone** [comment]
Yes.  I hooked it up to the conveyer system. Went into creative and gave it 10 of each ingot and told it to use the assembler. I also told the assembler to allow the factory to use it. There were also a lot of premade components in the system. I went back to survival and started the factory up. It still only wanted to grab the first component to build each projected block.

**Comment by BAM5** [comment]
I'll take a look at the source.

**Comment by BAM5** [comment]
Looks like there is a log for each way a projection target can be canceled.
Check out your log for nanites at
```<User Folder>\AppData\Roaming\SpaceEngineers\Storage\<Mod Name>_NaniteConstructionSystem\NaniteConstructionSystem.log```
If there is an entry then the mod is working as intended. Otherwise it is a bug.

The three issues it could have are 
* "CANCELLING Projection Target due to being disabled"
* "CANCELLING Projection Target due to power shortage"
* "CANCELLING Projection Target due to missing components"

**Comment by raysilverstone** [comment]
[NaniteConstructionSystem.log](https://github.com/nukeguard/NaniteConstructionSystem/files/1745727/NaniteConstructionSystem.log)
I cleared out the log and started a projector build again.  I don't see any Cancelling in the log.

**Comment by Fank** [comment]
@raysilverstone does still issue still appear with the current version?

**Comment by skyraze** [comment]
??? wait hold on isn't that what the projection beacon is supposed to do? it only builds the shell, the repair beacon is supposed to finish the job.

**Comment by Fank** [comment]
Yep

**Comment by nukeguard** [comment]
not sure why that was separate from construction, i mean both are intended to be built, maybe instead of projection beacon, only have a build projections option selected

**Comment by SplenectomY** [comment]
Projection targets have VERY different processing from construction targets, since the code needs to figure out which blocks CAN be built before deciding on a target. I.E. if it were to weld a block that doesn't have some sort of anchor, it would just float away. Therefore, without an extensive code rewrite, there's no need to mess with this as the current system works fine. Projection targets indeed will only receive the first material, just like in vanilla. At that point, the projection target no longer exists and it's made to be a construction target. What should happen is this: Projection upgrades are absurdly underpowered compared to construction upgrades and the two should be combined (OR a single projection upgrade should provide many more extra nanites), since who would want a bunch of upgrades that only provide one component to each block per extra nanite? Most of the work is during construction target processing, not projection target processing.

**Comment by SplenectomY** [comment]
My personal vote is to just remove projection upgrades and combine the functionality with construction upgrades. Thoughts? @Fank @nukeguard ?

**Comment by nukeguard** [comment]
makes sense to me, I think the projection upgrade only added projection nanite that would only place the first stage and then the construction nanite would come finish. I think it would be simpler to have the construction nanite just do both, if detecting a projection on grid or in are beacon space.

**Comment by SplenectomY** [comment]
Ok. I'll get to it.

**Comment by Fank** [comment]
Yea i think a upgrade that could create first stage like projection do now, makes it easier.

**Comment by SplenectomY** [comment]
Okay. Projection upgrades are removed. Construction upgrades now also improve projection efficiency. Projection beacons will now allow the entire block to be built rather than just  the first component, so there's no need for both a projection and a repair beacon on the same grid. All done!

**Comment by nukeguard** [comment]
so i can remove the models and definitions for the projection beacon and upgrades then.

**Comment by SplenectomY** [comment]
Yep. I've already removed the definitions, just need the models and icons removed.
