### ISSUE TITLE
Medical nanites permanently float around player after dying.

### ISSUE THREAD

**Issue by skyraze** [nukeguard/NaniteConstructionSystem#44]
the medical nanites are bugged in a way that causes them to stay floating around you if you die while being healed. the amount of nanites gradually increasing until all medical streams are in use on you.shutting off the nanites doesn't work, the player has to leave and reconnect or go outside of sync range for them to stop.

**Comment by SplenectomY** [comment]
I've reworked the way client and server-side nanite particles function. This "should" be fine now. It's been so long since this issue was opened that I would prefer a new one is opened if it pops up again. @skyraze if you can still recreate this error after 2.0 is released in a day or two, feel free to comment and I'll reopen

**Comment by bodyboarder2528** [comment]
this is still happening generally when i die if i was injured first and then die they hand around when i respawn
