### ISSUE TITLE
Long static nanites

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#62]
My russian player on the server got this, i don't know how or what they did but ...

![image](https://user-images.githubusercontent.com/1900106/45325850-56064f80-b552-11e8-98ad-57e944540ecb.png)
![image](https://user-images.githubusercontent.com/1900106/45325855-5acb0380-b552-11e8-9711-ef2ae0011b64.png)

**Comment by Fank** [comment]
They said that they are 12km far away from the base

**Comment by nukeguard** [comment]
that may have to do with the nanites trying to keep up with him and not despawning. Are those the healing nanites?

**Comment by nukeguard** [comment]
is that a possibility of minimum speed

**Comment by SplenectomY** [comment]
To the best of my knowledge, this should now be fixed, since I've overhauled the way nanite particles are spawned and cleaned up. This was likely due to a factory moving out of server sync range client side, giving the nanites nowhere to go to despawn. Since this issue is so old and so much development has taken place since then, let's create a new issue if it ever pops up again, and I'll take a deeper look.
