### ISSUE TITLE
Conveyors not connecting

### ISSUE THREAD

**Issue by Evan109** [nukeguard/NaniteConstructionSystem#74]
Conveyor tubes are red on all the sides I've tried thus far. I've even tried sides without conveyor ports but nothing seems to work.
Manually putting in components works though and it does weld stuff.

[Edit] All of the sudden working now? Going to do some testing....
         OK from what I can tell the bottom one works sometimes depending on something unknown

**Comment by bourgeoismd** [comment]
I'm getting this problem as well. Its just randomly picking a single component at a time but then just stops.

**Comment by SplenectomY** [comment]
Hey guys, are you using V1 or some test build of V2? The conveyor/connection system is completely reworked in V2 and is working fine.

**Comment by Evan109** [comment]
Okay, mine has just started working again after game restart. maybe that's the solution? Coveyors are green and its workin gr8.

**Comment by Evan109** [comment]
Splen:
this one. unsure if its V1 or V2
https://steamcommunity.com/sharedfiles/filedetails/?id=219757726&searchtext=nanite

**Comment by SplenectomY** [comment]
Right, so that's V1. As far as we're concerned, as long as it's not breaking the game, it's not on our priorities list. If you want to test out V2, you can either hope on this server 173.75.15.39:27016 or try the development build here https://steamcommunity.com/sharedfiles/filedetails/?id=1485968462 . The mining is not complete yet, and we are still ironing out the last few bugs before an official release, so try at your own risk.
